[package]
name = "primitives"
version = "0.0.1"
authors = ["sun"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "1.0"
actix = "0.8"
bytes = "0.4"
dirs = "1.0"
jsonrpc-parse = "0.1"

crypto= { path = "../crypto" }
