[package]
name = "teatree"
version = "0.0.0"
authors = ["Sun <huachuang20@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "the tree for all tea to mix. (Distributed and Blockchain Infrastructure)"
repository = "https://github.com/placefortea/teatree"
keywords = ["distributed", "blockchain", "infrastructure", "tea"]
license = "MIT/Apache-2.0"

[dependencies]

