[package]
name = "crypto"
version = "0.0.1"
authors = ["sun <huachuang20@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.5"
sha3 = "^0.7"
serde = "1.0"
serde_derive = "1.0"
ed25519-dalek = { version="1.0.0-pre.0", features = ["serde"]}

